// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.stonehiy.protobuf.proto.Header.proto

package com.stonehiy.protobuf.proto;

public final class HeaderInfo {
  private HeaderInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.stonehiy.protobuf.proto.Header)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *前4个字节是version
     * </pre>
     *
     * <code>uint32 version = 1;</code>
     */
    int getVersion();

    /**
     * <pre>
     *接下来的4个字节是个“魔法数字（magic_num）“，用来保证数据错位或丢包问题，常见的做法是，包头放几个约定好的特殊字符，包尾放几个约定好的特殊字符 约定好，发给你的协议，某几个字节位置，是0x 01020304 ，才是正常报文；
     * </pre>
     *
     * <code>uint32 magicNum = 2;</code>
     */
    int getMagicNum();

    /**
     * <pre>
     *接下来是command（命令号），用来区分是keepalive报文、业务报文、密钥交换报文等；
     * </pre>
     *
     * <code>uint32 cmd = 3;</code>
     */
    int getCmd();

    /**
     * <pre>
     *len（包体长度），告知服务端要接收多长的包体。
     * </pre>
     *
     * <code>uint32 len = 4;</code>
     */
    int getLen();

    /**
     * <pre>
     *数据
     * </pre>
     *
     * <code>bytes data = 5;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * <pre>
   *暂时无用
   * </pre>
   *
   * Protobuf type {@code com.stonehiy.protobuf.proto.Header}
   */
  public  static final class Header extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.stonehiy.protobuf.proto.Header)
      HeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Header.newBuilder() to construct.
    private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Header() {
      version_ = 0;
      magicNum_ = 0;
      cmd_ = 0;
      len_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Header(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              version_ = input.readUInt32();
              break;
            }
            case 16: {

              magicNum_ = input.readUInt32();
              break;
            }
            case 24: {

              cmd_ = input.readUInt32();
              break;
            }
            case 32: {

              len_ = input.readUInt32();
              break;
            }
            case 42: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stonehiy.protobuf.proto.HeaderInfo.internal_static_com_stonehiy_protobuf_proto_Header_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stonehiy.protobuf.proto.HeaderInfo.internal_static_com_stonehiy_protobuf_proto_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stonehiy.protobuf.proto.HeaderInfo.Header.class, com.stonehiy.protobuf.proto.HeaderInfo.Header.Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <pre>
     *前4个字节是version
     * </pre>
     *
     * <code>uint32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int MAGICNUM_FIELD_NUMBER = 2;
    private int magicNum_;
    /**
     * <pre>
     *接下来的4个字节是个“魔法数字（magic_num）“，用来保证数据错位或丢包问题，常见的做法是，包头放几个约定好的特殊字符，包尾放几个约定好的特殊字符 约定好，发给你的协议，某几个字节位置，是0x 01020304 ，才是正常报文；
     * </pre>
     *
     * <code>uint32 magicNum = 2;</code>
     */
    public int getMagicNum() {
      return magicNum_;
    }

    public static final int CMD_FIELD_NUMBER = 3;
    private int cmd_;
    /**
     * <pre>
     *接下来是command（命令号），用来区分是keepalive报文、业务报文、密钥交换报文等；
     * </pre>
     *
     * <code>uint32 cmd = 3;</code>
     */
    public int getCmd() {
      return cmd_;
    }

    public static final int LEN_FIELD_NUMBER = 4;
    private int len_;
    /**
     * <pre>
     *len（包体长度），告知服务端要接收多长的包体。
     * </pre>
     *
     * <code>uint32 len = 4;</code>
     */
    public int getLen() {
      return len_;
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     *数据
     * </pre>
     *
     * <code>bytes data = 5;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0) {
        output.writeUInt32(1, version_);
      }
      if (magicNum_ != 0) {
        output.writeUInt32(2, magicNum_);
      }
      if (cmd_ != 0) {
        output.writeUInt32(3, cmd_);
      }
      if (len_ != 0) {
        output.writeUInt32(4, len_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(5, data_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, version_);
      }
      if (magicNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, magicNum_);
      }
      if (cmd_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, cmd_);
      }
      if (len_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, len_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.stonehiy.protobuf.proto.HeaderInfo.Header)) {
        return super.equals(obj);
      }
      com.stonehiy.protobuf.proto.HeaderInfo.Header other = (com.stonehiy.protobuf.proto.HeaderInfo.Header) obj;

      boolean result = true;
      result = result && (getVersion()
          == other.getVersion());
      result = result && (getMagicNum()
          == other.getMagicNum());
      result = result && (getCmd()
          == other.getCmd());
      result = result && (getLen()
          == other.getLen());
      result = result && getData()
          .equals(other.getData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + MAGICNUM_FIELD_NUMBER;
      hash = (53 * hash) + getMagicNum();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd();
      hash = (37 * hash) + LEN_FIELD_NUMBER;
      hash = (53 * hash) + getLen();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.stonehiy.protobuf.proto.HeaderInfo.Header parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stonehiy.protobuf.proto.HeaderInfo.Header parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stonehiy.protobuf.proto.HeaderInfo.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stonehiy.protobuf.proto.HeaderInfo.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stonehiy.protobuf.proto.HeaderInfo.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stonehiy.protobuf.proto.HeaderInfo.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stonehiy.protobuf.proto.HeaderInfo.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stonehiy.protobuf.proto.HeaderInfo.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stonehiy.protobuf.proto.HeaderInfo.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.stonehiy.protobuf.proto.HeaderInfo.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stonehiy.protobuf.proto.HeaderInfo.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stonehiy.protobuf.proto.HeaderInfo.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.stonehiy.protobuf.proto.HeaderInfo.Header prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *暂时无用
     * </pre>
     *
     * Protobuf type {@code com.stonehiy.protobuf.proto.Header}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.stonehiy.protobuf.proto.Header)
        com.stonehiy.protobuf.proto.HeaderInfo.HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stonehiy.protobuf.proto.HeaderInfo.internal_static_com_stonehiy_protobuf_proto_Header_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stonehiy.protobuf.proto.HeaderInfo.internal_static_com_stonehiy_protobuf_proto_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stonehiy.protobuf.proto.HeaderInfo.Header.class, com.stonehiy.protobuf.proto.HeaderInfo.Header.Builder.class);
      }

      // Construct using com.stonehiy.protobuf.proto.HeaderInfo.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        version_ = 0;

        magicNum_ = 0;

        cmd_ = 0;

        len_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stonehiy.protobuf.proto.HeaderInfo.internal_static_com_stonehiy_protobuf_proto_Header_descriptor;
      }

      public com.stonehiy.protobuf.proto.HeaderInfo.Header getDefaultInstanceForType() {
        return com.stonehiy.protobuf.proto.HeaderInfo.Header.getDefaultInstance();
      }

      public com.stonehiy.protobuf.proto.HeaderInfo.Header build() {
        com.stonehiy.protobuf.proto.HeaderInfo.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.stonehiy.protobuf.proto.HeaderInfo.Header buildPartial() {
        com.stonehiy.protobuf.proto.HeaderInfo.Header result = new com.stonehiy.protobuf.proto.HeaderInfo.Header(this);
        result.version_ = version_;
        result.magicNum_ = magicNum_;
        result.cmd_ = cmd_;
        result.len_ = len_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stonehiy.protobuf.proto.HeaderInfo.Header) {
          return mergeFrom((com.stonehiy.protobuf.proto.HeaderInfo.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stonehiy.protobuf.proto.HeaderInfo.Header other) {
        if (other == com.stonehiy.protobuf.proto.HeaderInfo.Header.getDefaultInstance()) return this;
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getMagicNum() != 0) {
          setMagicNum(other.getMagicNum());
        }
        if (other.getCmd() != 0) {
          setCmd(other.getCmd());
        }
        if (other.getLen() != 0) {
          setLen(other.getLen());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stonehiy.protobuf.proto.HeaderInfo.Header parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stonehiy.protobuf.proto.HeaderInfo.Header) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int version_ ;
      /**
       * <pre>
       *前4个字节是version
       * </pre>
       *
       * <code>uint32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       *前4个字节是version
       * </pre>
       *
       * <code>uint32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *前4个字节是version
       * </pre>
       *
       * <code>uint32 version = 1;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private int magicNum_ ;
      /**
       * <pre>
       *接下来的4个字节是个“魔法数字（magic_num）“，用来保证数据错位或丢包问题，常见的做法是，包头放几个约定好的特殊字符，包尾放几个约定好的特殊字符 约定好，发给你的协议，某几个字节位置，是0x 01020304 ，才是正常报文；
       * </pre>
       *
       * <code>uint32 magicNum = 2;</code>
       */
      public int getMagicNum() {
        return magicNum_;
      }
      /**
       * <pre>
       *接下来的4个字节是个“魔法数字（magic_num）“，用来保证数据错位或丢包问题，常见的做法是，包头放几个约定好的特殊字符，包尾放几个约定好的特殊字符 约定好，发给你的协议，某几个字节位置，是0x 01020304 ，才是正常报文；
       * </pre>
       *
       * <code>uint32 magicNum = 2;</code>
       */
      public Builder setMagicNum(int value) {
        
        magicNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接下来的4个字节是个“魔法数字（magic_num）“，用来保证数据错位或丢包问题，常见的做法是，包头放几个约定好的特殊字符，包尾放几个约定好的特殊字符 约定好，发给你的协议，某几个字节位置，是0x 01020304 ，才是正常报文；
       * </pre>
       *
       * <code>uint32 magicNum = 2;</code>
       */
      public Builder clearMagicNum() {
        
        magicNum_ = 0;
        onChanged();
        return this;
      }

      private int cmd_ ;
      /**
       * <pre>
       *接下来是command（命令号），用来区分是keepalive报文、业务报文、密钥交换报文等；
       * </pre>
       *
       * <code>uint32 cmd = 3;</code>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <pre>
       *接下来是command（命令号），用来区分是keepalive报文、业务报文、密钥交换报文等；
       * </pre>
       *
       * <code>uint32 cmd = 3;</code>
       */
      public Builder setCmd(int value) {
        
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接下来是command（命令号），用来区分是keepalive报文、业务报文、密钥交换报文等；
       * </pre>
       *
       * <code>uint32 cmd = 3;</code>
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }

      private int len_ ;
      /**
       * <pre>
       *len（包体长度），告知服务端要接收多长的包体。
       * </pre>
       *
       * <code>uint32 len = 4;</code>
       */
      public int getLen() {
        return len_;
      }
      /**
       * <pre>
       *len（包体长度），告知服务端要接收多长的包体。
       * </pre>
       *
       * <code>uint32 len = 4;</code>
       */
      public Builder setLen(int value) {
        
        len_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *len（包体长度），告知服务端要接收多长的包体。
       * </pre>
       *
       * <code>uint32 len = 4;</code>
       */
      public Builder clearLen() {
        
        len_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *数据
       * </pre>
       *
       * <code>bytes data = 5;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       *数据
       * </pre>
       *
       * <code>bytes data = 5;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *数据
       * </pre>
       *
       * <code>bytes data = 5;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.stonehiy.protobuf.proto.Header)
    }

    // @@protoc_insertion_point(class_scope:com.stonehiy.protobuf.proto.Header)
    private static final com.stonehiy.protobuf.proto.HeaderInfo.Header DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.stonehiy.protobuf.proto.HeaderInfo.Header();
    }

    public static com.stonehiy.protobuf.proto.HeaderInfo.Header getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Header>
        PARSER = new com.google.protobuf.AbstractParser<Header>() {
      public Header parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Header(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Header> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Header> getParserForType() {
      return PARSER;
    }

    public com.stonehiy.protobuf.proto.HeaderInfo.Header getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stonehiy_protobuf_proto_Header_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stonehiy_protobuf_proto_Header_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(com.stonehiy.protobuf.proto.Header.pro" +
      "to\022\033com.stonehiy.protobuf.proto\"S\n\006Heade" +
      "r\022\017\n\007version\030\001 \001(\r\022\020\n\010magicNum\030\002 \001(\r\022\013\n\003" +
      "cmd\030\003 \001(\r\022\013\n\003len\030\004 \001(\r\022\014\n\004data\030\005 \001(\014B\014B\n" +
      "HeaderInfob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_stonehiy_protobuf_proto_Header_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stonehiy_protobuf_proto_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stonehiy_protobuf_proto_Header_descriptor,
        new java.lang.String[] { "Version", "MagicNum", "Cmd", "Len", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
