// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.stonehiy.protobuf.proto.User.proto

package com.stonehiy.protobuf.proto;

public final class UserInfo {
  private UserInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.stonehiy.protobuf.proto.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *uuid
     * </pre>
     *
     * <code>string uuid = 1;</code>
     */
    java.lang.String getUuid();
    /**
     * <pre>
     *uuid
     * </pre>
     *
     * <code>string uuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <pre>
     *id
     * </pre>
     *
     * <code>int32 id = 2;</code>
     */
    int getId();

    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>string userName = 3;</code>
     */
    java.lang.String getUserName();
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>string userName = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <pre>
     *密码
     * </pre>
     *
     * <code>string passWord = 4;</code>
     */
    java.lang.String getPassWord();
    /**
     * <pre>
     *密码
     * </pre>
     *
     * <code>string passWord = 4;</code>
     */
    com.google.protobuf.ByteString
        getPassWordBytes();

    /**
     * <pre>
     *昵称
     * </pre>
     *
     * <code>string nickName = 5;</code>
     */
    java.lang.String getNickName();
    /**
     * <pre>
     *昵称
     * </pre>
     *
     * <code>string nickName = 5;</code>
     */
    com.google.protobuf.ByteString
        getNickNameBytes();

    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string createTime = 6;</code>
     */
    java.lang.String getCreateTime();
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string createTime = 6;</code>
     */
    com.google.protobuf.ByteString
        getCreateTimeBytes();

    /**
     * <pre>
     *更新时间
     * </pre>
     *
     * <code>string updateTime = 7;</code>
     */
    java.lang.String getUpdateTime();
    /**
     * <pre>
     *更新时间
     * </pre>
     *
     * <code>string updateTime = 7;</code>
     */
    com.google.protobuf.ByteString
        getUpdateTimeBytes();

    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>int32 gender = 8;</code>
     */
    int getGender();

    /**
     * <pre>
     *最后登录IP
     * </pre>
     *
     * <code>string lastLoginip = 9;</code>
     */
    java.lang.String getLastLoginip();
    /**
     * <pre>
     *最后登录IP
     * </pre>
     *
     * <code>string lastLoginip = 9;</code>
     */
    com.google.protobuf.ByteString
        getLastLoginipBytes();

    /**
     * <pre>
     *最后登录时间
     * </pre>
     *
     * <code>string lastLoginTime = 10;</code>
     */
    java.lang.String getLastLoginTime();
    /**
     * <pre>
     *最后登录时间
     * </pre>
     *
     * <code>string lastLoginTime = 10;</code>
     */
    com.google.protobuf.ByteString
        getLastLoginTimeBytes();

    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>string avatar = 11;</code>
     */
    java.lang.String getAvatar();
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>string avatar = 11;</code>
     */
    com.google.protobuf.ByteString
        getAvatarBytes();

    /**
     * <pre>
     *是否删除
     * </pre>
     *
     * <code>int32 deleted = 12;</code>
     */
    int getDeleted();
  }
  /**
   * <pre>
   *暂时无用
   * </pre>
   *
   * Protobuf type {@code com.stonehiy.protobuf.proto.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.stonehiy.protobuf.proto.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      uuid_ = "";
      id_ = 0;
      userName_ = "";
      passWord_ = "";
      nickName_ = "";
      createTime_ = "";
      updateTime_ = "";
      gender_ = 0;
      lastLoginip_ = "";
      lastLoginTime_ = "";
      avatar_ = "";
      deleted_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uuid_ = s;
              break;
            }
            case 16: {

              id_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              passWord_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              nickName_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              createTime_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              updateTime_ = s;
              break;
            }
            case 64: {

              gender_ = input.readInt32();
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              lastLoginip_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              lastLoginTime_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              avatar_ = s;
              break;
            }
            case 96: {

              deleted_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stonehiy.protobuf.proto.UserInfo.internal_static_com_stonehiy_protobuf_proto_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stonehiy.protobuf.proto.UserInfo.internal_static_com_stonehiy_protobuf_proto_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stonehiy.protobuf.proto.UserInfo.User.class, com.stonehiy.protobuf.proto.UserInfo.User.Builder.class);
    }

    public static final int UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uuid_;
    /**
     * <pre>
     *uuid
     * </pre>
     *
     * <code>string uuid = 1;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *uuid
     * </pre>
     *
     * <code>string uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <pre>
     *id
     * </pre>
     *
     * <code>int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int USERNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object userName_;
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>string userName = 3;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>string userName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 4;
    private volatile java.lang.Object passWord_;
    /**
     * <pre>
     *密码
     * </pre>
     *
     * <code>string passWord = 4;</code>
     */
    public java.lang.String getPassWord() {
      java.lang.Object ref = passWord_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        passWord_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *密码
     * </pre>
     *
     * <code>string passWord = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPassWordBytes() {
      java.lang.Object ref = passWord_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        passWord_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICKNAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object nickName_;
    /**
     * <pre>
     *昵称
     * </pre>
     *
     * <code>string nickName = 5;</code>
     */
    public java.lang.String getNickName() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nickName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *昵称
     * </pre>
     *
     * <code>string nickName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETIME_FIELD_NUMBER = 6;
    private volatile java.lang.Object createTime_;
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string createTime = 6;</code>
     */
    public java.lang.String getCreateTime() {
      java.lang.Object ref = createTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createTime_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string createTime = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCreateTimeBytes() {
      java.lang.Object ref = createTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPDATETIME_FIELD_NUMBER = 7;
    private volatile java.lang.Object updateTime_;
    /**
     * <pre>
     *更新时间
     * </pre>
     *
     * <code>string updateTime = 7;</code>
     */
    public java.lang.String getUpdateTime() {
      java.lang.Object ref = updateTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updateTime_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *更新时间
     * </pre>
     *
     * <code>string updateTime = 7;</code>
     */
    public com.google.protobuf.ByteString
        getUpdateTimeBytes() {
      java.lang.Object ref = updateTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 8;
    private int gender_;
    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>int32 gender = 8;</code>
     */
    public int getGender() {
      return gender_;
    }

    public static final int LASTLOGINIP_FIELD_NUMBER = 9;
    private volatile java.lang.Object lastLoginip_;
    /**
     * <pre>
     *最后登录IP
     * </pre>
     *
     * <code>string lastLoginip = 9;</code>
     */
    public java.lang.String getLastLoginip() {
      java.lang.Object ref = lastLoginip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastLoginip_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *最后登录IP
     * </pre>
     *
     * <code>string lastLoginip = 9;</code>
     */
    public com.google.protobuf.ByteString
        getLastLoginipBytes() {
      java.lang.Object ref = lastLoginip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastLoginip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTLOGINTIME_FIELD_NUMBER = 10;
    private volatile java.lang.Object lastLoginTime_;
    /**
     * <pre>
     *最后登录时间
     * </pre>
     *
     * <code>string lastLoginTime = 10;</code>
     */
    public java.lang.String getLastLoginTime() {
      java.lang.Object ref = lastLoginTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastLoginTime_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *最后登录时间
     * </pre>
     *
     * <code>string lastLoginTime = 10;</code>
     */
    public com.google.protobuf.ByteString
        getLastLoginTimeBytes() {
      java.lang.Object ref = lastLoginTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastLoginTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVATAR_FIELD_NUMBER = 11;
    private volatile java.lang.Object avatar_;
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>string avatar = 11;</code>
     */
    public java.lang.String getAvatar() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatar_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>string avatar = 11;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DELETED_FIELD_NUMBER = 12;
    private int deleted_;
    /**
     * <pre>
     *是否删除
     * </pre>
     *
     * <code>int32 deleted = 12;</code>
     */
    public int getDeleted() {
      return deleted_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
      }
      if (id_ != 0) {
        output.writeInt32(2, id_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userName_);
      }
      if (!getPassWordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, passWord_);
      }
      if (!getNickNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, nickName_);
      }
      if (!getCreateTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, createTime_);
      }
      if (!getUpdateTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, updateTime_);
      }
      if (gender_ != 0) {
        output.writeInt32(8, gender_);
      }
      if (!getLastLoginipBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, lastLoginip_);
      }
      if (!getLastLoginTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, lastLoginTime_);
      }
      if (!getAvatarBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, avatar_);
      }
      if (deleted_ != 0) {
        output.writeInt32(12, deleted_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userName_);
      }
      if (!getPassWordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, passWord_);
      }
      if (!getNickNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, nickName_);
      }
      if (!getCreateTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, createTime_);
      }
      if (!getUpdateTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, updateTime_);
      }
      if (gender_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, gender_);
      }
      if (!getLastLoginipBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, lastLoginip_);
      }
      if (!getLastLoginTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, lastLoginTime_);
      }
      if (!getAvatarBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, avatar_);
      }
      if (deleted_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, deleted_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.stonehiy.protobuf.proto.UserInfo.User)) {
        return super.equals(obj);
      }
      com.stonehiy.protobuf.proto.UserInfo.User other = (com.stonehiy.protobuf.proto.UserInfo.User) obj;

      boolean result = true;
      result = result && getUuid()
          .equals(other.getUuid());
      result = result && (getId()
          == other.getId());
      result = result && getUserName()
          .equals(other.getUserName());
      result = result && getPassWord()
          .equals(other.getPassWord());
      result = result && getNickName()
          .equals(other.getNickName());
      result = result && getCreateTime()
          .equals(other.getCreateTime());
      result = result && getUpdateTime()
          .equals(other.getUpdateTime());
      result = result && (getGender()
          == other.getGender());
      result = result && getLastLoginip()
          .equals(other.getLastLoginip());
      result = result && getLastLoginTime()
          .equals(other.getLastLoginTime());
      result = result && getAvatar()
          .equals(other.getAvatar());
      result = result && (getDeleted()
          == other.getDeleted());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassWord().hashCode();
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickName().hashCode();
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getCreateTime().hashCode();
      hash = (37 * hash) + UPDATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateTime().hashCode();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + getGender();
      hash = (37 * hash) + LASTLOGINIP_FIELD_NUMBER;
      hash = (53 * hash) + getLastLoginip().hashCode();
      hash = (37 * hash) + LASTLOGINTIME_FIELD_NUMBER;
      hash = (53 * hash) + getLastLoginTime().hashCode();
      hash = (37 * hash) + AVATAR_FIELD_NUMBER;
      hash = (53 * hash) + getAvatar().hashCode();
      hash = (37 * hash) + DELETED_FIELD_NUMBER;
      hash = (53 * hash) + getDeleted();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.stonehiy.protobuf.proto.UserInfo.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stonehiy.protobuf.proto.UserInfo.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stonehiy.protobuf.proto.UserInfo.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stonehiy.protobuf.proto.UserInfo.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stonehiy.protobuf.proto.UserInfo.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stonehiy.protobuf.proto.UserInfo.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stonehiy.protobuf.proto.UserInfo.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stonehiy.protobuf.proto.UserInfo.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stonehiy.protobuf.proto.UserInfo.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.stonehiy.protobuf.proto.UserInfo.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stonehiy.protobuf.proto.UserInfo.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stonehiy.protobuf.proto.UserInfo.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.stonehiy.protobuf.proto.UserInfo.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *暂时无用
     * </pre>
     *
     * Protobuf type {@code com.stonehiy.protobuf.proto.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.stonehiy.protobuf.proto.User)
        com.stonehiy.protobuf.proto.UserInfo.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stonehiy.protobuf.proto.UserInfo.internal_static_com_stonehiy_protobuf_proto_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stonehiy.protobuf.proto.UserInfo.internal_static_com_stonehiy_protobuf_proto_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stonehiy.protobuf.proto.UserInfo.User.class, com.stonehiy.protobuf.proto.UserInfo.User.Builder.class);
      }

      // Construct using com.stonehiy.protobuf.proto.UserInfo.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uuid_ = "";

        id_ = 0;

        userName_ = "";

        passWord_ = "";

        nickName_ = "";

        createTime_ = "";

        updateTime_ = "";

        gender_ = 0;

        lastLoginip_ = "";

        lastLoginTime_ = "";

        avatar_ = "";

        deleted_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stonehiy.protobuf.proto.UserInfo.internal_static_com_stonehiy_protobuf_proto_User_descriptor;
      }

      public com.stonehiy.protobuf.proto.UserInfo.User getDefaultInstanceForType() {
        return com.stonehiy.protobuf.proto.UserInfo.User.getDefaultInstance();
      }

      public com.stonehiy.protobuf.proto.UserInfo.User build() {
        com.stonehiy.protobuf.proto.UserInfo.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.stonehiy.protobuf.proto.UserInfo.User buildPartial() {
        com.stonehiy.protobuf.proto.UserInfo.User result = new com.stonehiy.protobuf.proto.UserInfo.User(this);
        result.uuid_ = uuid_;
        result.id_ = id_;
        result.userName_ = userName_;
        result.passWord_ = passWord_;
        result.nickName_ = nickName_;
        result.createTime_ = createTime_;
        result.updateTime_ = updateTime_;
        result.gender_ = gender_;
        result.lastLoginip_ = lastLoginip_;
        result.lastLoginTime_ = lastLoginTime_;
        result.avatar_ = avatar_;
        result.deleted_ = deleted_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stonehiy.protobuf.proto.UserInfo.User) {
          return mergeFrom((com.stonehiy.protobuf.proto.UserInfo.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stonehiy.protobuf.proto.UserInfo.User other) {
        if (other == com.stonehiy.protobuf.proto.UserInfo.User.getDefaultInstance()) return this;
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getPassWord().isEmpty()) {
          passWord_ = other.passWord_;
          onChanged();
        }
        if (!other.getNickName().isEmpty()) {
          nickName_ = other.nickName_;
          onChanged();
        }
        if (!other.getCreateTime().isEmpty()) {
          createTime_ = other.createTime_;
          onChanged();
        }
        if (!other.getUpdateTime().isEmpty()) {
          updateTime_ = other.updateTime_;
          onChanged();
        }
        if (other.getGender() != 0) {
          setGender(other.getGender());
        }
        if (!other.getLastLoginip().isEmpty()) {
          lastLoginip_ = other.lastLoginip_;
          onChanged();
        }
        if (!other.getLastLoginTime().isEmpty()) {
          lastLoginTime_ = other.lastLoginTime_;
          onChanged();
        }
        if (!other.getAvatar().isEmpty()) {
          avatar_ = other.avatar_;
          onChanged();
        }
        if (other.getDeleted() != 0) {
          setDeleted(other.getDeleted());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stonehiy.protobuf.proto.UserInfo.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stonehiy.protobuf.proto.UserInfo.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uuid_ = "";
      /**
       * <pre>
       *uuid
       * </pre>
       *
       * <code>string uuid = 1;</code>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *uuid
       * </pre>
       *
       * <code>string uuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *uuid
       * </pre>
       *
       * <code>string uuid = 1;</code>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *uuid
       * </pre>
       *
       * <code>string uuid = 1;</code>
       */
      public Builder clearUuid() {
        
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *uuid
       * </pre>
       *
       * <code>string uuid = 1;</code>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uuid_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       *id
       * </pre>
       *
       * <code>int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       *id
       * </pre>
       *
       * <code>int32 id = 2;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *id
       * </pre>
       *
       * <code>int32 id = 2;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string userName = 3;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string userName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string userName = 3;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string userName = 3;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string userName = 3;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object passWord_ = "";
      /**
       * <pre>
       *密码
       * </pre>
       *
       * <code>string passWord = 4;</code>
       */
      public java.lang.String getPassWord() {
        java.lang.Object ref = passWord_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          passWord_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *密码
       * </pre>
       *
       * <code>string passWord = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPassWordBytes() {
        java.lang.Object ref = passWord_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          passWord_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *密码
       * </pre>
       *
       * <code>string passWord = 4;</code>
       */
      public Builder setPassWord(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        passWord_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *密码
       * </pre>
       *
       * <code>string passWord = 4;</code>
       */
      public Builder clearPassWord() {
        
        passWord_ = getDefaultInstance().getPassWord();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *密码
       * </pre>
       *
       * <code>string passWord = 4;</code>
       */
      public Builder setPassWordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        passWord_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nickName_ = "";
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>string nickName = 5;</code>
       */
      public java.lang.String getNickName() {
        java.lang.Object ref = nickName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nickName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>string nickName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getNickNameBytes() {
        java.lang.Object ref = nickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>string nickName = 5;</code>
       */
      public Builder setNickName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>string nickName = 5;</code>
       */
      public Builder clearNickName() {
        
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>string nickName = 5;</code>
       */
      public Builder setNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nickName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object createTime_ = "";
      /**
       * <pre>
       *创建时间
       * </pre>
       *
       * <code>string createTime = 6;</code>
       */
      public java.lang.String getCreateTime() {
        java.lang.Object ref = createTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          createTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *创建时间
       * </pre>
       *
       * <code>string createTime = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCreateTimeBytes() {
        java.lang.Object ref = createTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          createTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *创建时间
       * </pre>
       *
       * <code>string createTime = 6;</code>
       */
      public Builder setCreateTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *创建时间
       * </pre>
       *
       * <code>string createTime = 6;</code>
       */
      public Builder clearCreateTime() {
        
        createTime_ = getDefaultInstance().getCreateTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *创建时间
       * </pre>
       *
       * <code>string createTime = 6;</code>
       */
      public Builder setCreateTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        createTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object updateTime_ = "";
      /**
       * <pre>
       *更新时间
       * </pre>
       *
       * <code>string updateTime = 7;</code>
       */
      public java.lang.String getUpdateTime() {
        java.lang.Object ref = updateTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          updateTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *更新时间
       * </pre>
       *
       * <code>string updateTime = 7;</code>
       */
      public com.google.protobuf.ByteString
          getUpdateTimeBytes() {
        java.lang.Object ref = updateTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          updateTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *更新时间
       * </pre>
       *
       * <code>string updateTime = 7;</code>
       */
      public Builder setUpdateTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        updateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *更新时间
       * </pre>
       *
       * <code>string updateTime = 7;</code>
       */
      public Builder clearUpdateTime() {
        
        updateTime_ = getDefaultInstance().getUpdateTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *更新时间
       * </pre>
       *
       * <code>string updateTime = 7;</code>
       */
      public Builder setUpdateTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        updateTime_ = value;
        onChanged();
        return this;
      }

      private int gender_ ;
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>int32 gender = 8;</code>
       */
      public int getGender() {
        return gender_;
      }
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>int32 gender = 8;</code>
       */
      public Builder setGender(int value) {
        
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>int32 gender = 8;</code>
       */
      public Builder clearGender() {
        
        gender_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object lastLoginip_ = "";
      /**
       * <pre>
       *最后登录IP
       * </pre>
       *
       * <code>string lastLoginip = 9;</code>
       */
      public java.lang.String getLastLoginip() {
        java.lang.Object ref = lastLoginip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastLoginip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *最后登录IP
       * </pre>
       *
       * <code>string lastLoginip = 9;</code>
       */
      public com.google.protobuf.ByteString
          getLastLoginipBytes() {
        java.lang.Object ref = lastLoginip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastLoginip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *最后登录IP
       * </pre>
       *
       * <code>string lastLoginip = 9;</code>
       */
      public Builder setLastLoginip(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastLoginip_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *最后登录IP
       * </pre>
       *
       * <code>string lastLoginip = 9;</code>
       */
      public Builder clearLastLoginip() {
        
        lastLoginip_ = getDefaultInstance().getLastLoginip();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *最后登录IP
       * </pre>
       *
       * <code>string lastLoginip = 9;</code>
       */
      public Builder setLastLoginipBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastLoginip_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastLoginTime_ = "";
      /**
       * <pre>
       *最后登录时间
       * </pre>
       *
       * <code>string lastLoginTime = 10;</code>
       */
      public java.lang.String getLastLoginTime() {
        java.lang.Object ref = lastLoginTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastLoginTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *最后登录时间
       * </pre>
       *
       * <code>string lastLoginTime = 10;</code>
       */
      public com.google.protobuf.ByteString
          getLastLoginTimeBytes() {
        java.lang.Object ref = lastLoginTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastLoginTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *最后登录时间
       * </pre>
       *
       * <code>string lastLoginTime = 10;</code>
       */
      public Builder setLastLoginTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastLoginTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *最后登录时间
       * </pre>
       *
       * <code>string lastLoginTime = 10;</code>
       */
      public Builder clearLastLoginTime() {
        
        lastLoginTime_ = getDefaultInstance().getLastLoginTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *最后登录时间
       * </pre>
       *
       * <code>string lastLoginTime = 10;</code>
       */
      public Builder setLastLoginTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastLoginTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object avatar_ = "";
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>string avatar = 11;</code>
       */
      public java.lang.String getAvatar() {
        java.lang.Object ref = avatar_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          avatar_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>string avatar = 11;</code>
       */
      public com.google.protobuf.ByteString
          getAvatarBytes() {
        java.lang.Object ref = avatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          avatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>string avatar = 11;</code>
       */
      public Builder setAvatar(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        avatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>string avatar = 11;</code>
       */
      public Builder clearAvatar() {
        
        avatar_ = getDefaultInstance().getAvatar();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>string avatar = 11;</code>
       */
      public Builder setAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        avatar_ = value;
        onChanged();
        return this;
      }

      private int deleted_ ;
      /**
       * <pre>
       *是否删除
       * </pre>
       *
       * <code>int32 deleted = 12;</code>
       */
      public int getDeleted() {
        return deleted_;
      }
      /**
       * <pre>
       *是否删除
       * </pre>
       *
       * <code>int32 deleted = 12;</code>
       */
      public Builder setDeleted(int value) {
        
        deleted_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否删除
       * </pre>
       *
       * <code>int32 deleted = 12;</code>
       */
      public Builder clearDeleted() {
        
        deleted_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.stonehiy.protobuf.proto.User)
    }

    // @@protoc_insertion_point(class_scope:com.stonehiy.protobuf.proto.User)
    private static final com.stonehiy.protobuf.proto.UserInfo.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.stonehiy.protobuf.proto.UserInfo.User();
    }

    public static com.stonehiy.protobuf.proto.UserInfo.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public com.stonehiy.protobuf.proto.UserInfo.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stonehiy_protobuf_proto_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stonehiy_protobuf_proto_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&com.stonehiy.protobuf.proto.User.proto" +
      "\022\033com.stonehiy.protobuf.proto\"\333\001\n\004User\022\014" +
      "\n\004uuid\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\020\n\010userName\030\003 \001" +
      "(\t\022\020\n\010passWord\030\004 \001(\t\022\020\n\010nickName\030\005 \001(\t\022\022" +
      "\n\ncreateTime\030\006 \001(\t\022\022\n\nupdateTime\030\007 \001(\t\022\016" +
      "\n\006gender\030\010 \001(\005\022\023\n\013lastLoginip\030\t \001(\t\022\025\n\rl" +
      "astLoginTime\030\n \001(\t\022\016\n\006avatar\030\013 \001(\t\022\017\n\007de" +
      "leted\030\014 \001(\005B\nB\010UserInfob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_stonehiy_protobuf_proto_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stonehiy_protobuf_proto_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stonehiy_protobuf_proto_User_descriptor,
        new java.lang.String[] { "Uuid", "Id", "UserName", "PassWord", "NickName", "CreateTime", "UpdateTime", "Gender", "LastLoginip", "LastLoginTime", "Avatar", "Deleted", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
